#!/pkg/bin/perl -w
use strict;
use Colobus qw(%config %feeds %groups read_config);
use Carp;

read_config();

for my $feed (keys %feeds) {
  #next unless $feed eq "nntpfeed";
  print "processing $feed\n" if -t STDIN;
  my $host = $feeds{$feed}->{host};
  my %args;
  %args = (silent => 1) unless -t STDIN;
  run("tcpclient -RHl0 $host nntp ./colobus -s $feed", { %args, failok => 1 });
}

sub run {
  my @ar = @_;
  my $parms = ref $ar[-1] eq "HASH" ? pop @ar : {};

  print "Running: ", join(" ",@ar), "\n" unless $parms->{silent};

  return 1 if system (@ar) == 0;

  my $exit_value = $? >> 8;
  return 0 if $parms->{fail_silent_if}
           && $exit_value == $parms->{fail_silent_if};

  my $msg = "system @ar failed: $exit_value ($?)";
  croak $msg unless $parms->{failok};
  print "$msg\n" ;
  return 0;
}

1;
